### PR TITLE
Added configuration option ignore_old_files

### PR DESCRIPTION
**Pull request by imacube**
Added the configuration file option, ignore_old_files, so that files older then n days are ignored. The default behavior is to watch all files matched in the configurations.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Why not just delete those files?

**Comment by imacube** [comment]
The systems I'm running beaver on have large enough hard drives that old logs don't need to be deleted and are kept as a local log backup.

**Comment by josegonzalez** [comment]
Then move them out or archive them? This seems like a hack for improper log retention policies, and makes me hesitant to add it as a result.

**Comment by imacube** [comment]
In my systems case it was easier to patch beaver then to handle archiving the log files. If you feel that this code doesn't belong then I'll close the pull request.

**Comment by coregear** [comment]
yes I need this, we need less impact to prod systems, so I'll use it! thanks!

**Comment by viniiciusconceicao** [comment]
Does this option still exist ? if it does, I couldn't find it on the documentation.

**Comment by josegonzalez** [comment]
Doesn't look like it was ever documented. Feel free to add docs for it.

**Pull request merged**
