### PR TITLE
added ssl-tcp key file support

### PR DESCRIPTION
**Pull request by Babbleshack**
add support for ssl-tcp keyfile

### CODE REVIEW

**Comment by josegonzalez** [comment]
Can you add documentation for this?

**Comment by Babbleshack** [comment]
Just specifying the extra attributes for ssl?

**Comment by Babbleshack** [comment]
some documentation has been added, you never replied so I just added some explanation to the config attribs

**Comment by josegonzalez** [comment]
Thanks for the pr! 

(I was commuting to work)

**Comment by Babbleshack** [comment]
;)

**Pull request merged**
