### PR TITLE
Bug fix for sqs transport

### PR DESCRIPTION
**Pull request by JamieCressey**
Fixing a bug in SQS transport when sending to multiple queues.

### CODE REVIEW

**Comment by josegonzalez** [comment]
What is the bug?

**Comment by JamieCressey** [comment]
We're currently trying to call `.write()` on a dict object instead of the SQS object(s) within that dictionary.

This was introduced following the merge of my last two PRs, and is only affecting users who try and enable the `sqs_bulk_lines` feature.

**Comment by josegonzalez** [comment]
Can you update the commit message to say that instead? Also, might be worth renaming the `_queue` attribute to be plural.

**Comment by JamieCressey** [comment]
Sure, that's been done, thanks!

**Comment by JamieCressey** [comment]
Thanks @josegonzalez. Any chance of a bug fix release for this, please?

**Comment by josegonzalez** [comment]
Done.

@JamieCressey Side note: would you and/or your company be open to helping maintain beaver/fix issues/merge PRs?

**Comment by JamieCressey** [comment]
@josegonzalez sure, happy to help. @lmorfitt came up with some ideas around the tests so pulling him in too.

**Comment by josegonzalez** [comment]
Added the both of you as collaborators!

**Comment by josegonzalez** [comment]
@JamieCressey are you on irc by any chance? I'm `savant` there, or on [hangops slack](http://signup.hangops.com/) as the same name.

**Pull request merged**
