### PR TITLE
Ability to send multiple log entries per single SQS message

### PR DESCRIPTION
**Pull request by JamieCressey**
In larger environments the requests made to SQS to read\write messages can soon add up, coupled with AWS charging in 64kb chunks, sending (and LogStash retrieving) single log entries per SQS message can soon become expensive.

This change adds a config flag `sqs_bulk_lines` (as to have no adverse affect to current deployments) to allow users to group messages in a similar way to the `write_bulk` function currently work (grouping messages up to a max of 256kb), only they are sent as an array list in a single SQS message rather than being sent as separate messages in one transaction.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Mind rebasing this onto master?

**Comment by JamieCressey** [comment]
Merged. Thanks for the heads up.

**Comment by JamieCressey** [comment]
Any chance of getting this merged? @josegonzalez. A new release would be awesome, thanks in advanced.

**Comment by josegonzalez** [comment]
Sorry was afk for a bit.

**Pull request merged**
