### PR TITLE
Adding AWS SNS as a transport option

### PR DESCRIPTION
**Pull request by JamieCressey**
I'm currently building out a test logstash environment and to allow me to;

1) replicate the log entries being processed in prod
2) enable/disable sending logs to test as and when required

I decided to use SNS as the transport layer which Logstash SQS queues can then subscribe to.

### CODE REVIEW

**Comment by JamieCressey** [comment]
@josegonzalez is there an issue with the tests? They timeout locally and on Travis without providing any error message.

**Comment by josegonzalez** [comment]
Can you rebase onto master?

**Comment by JamieCressey** [comment]
Thanks @josegonzalez. Rebased and tests passed.

**Comment by josegonzalez** [comment]
Merged and released.

**Pull request merged**
